// Generated types for Supabase - will be auto-generated by supabase gen types
// For now, we define the expected structure

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          name: string;
          email: string | null;
          dietary_goals: DietaryGoals | null;
          preferences: UserPreferences | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['users']['Insert']>;
      };
      family_members: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          dietary_restrictions: string[];
          preferences: MemberPreferences | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['family_members']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['family_members']['Insert']>;
      };
      recipes: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          ingredients: Ingredient[];
          instructions: string[];
          nutrition: NutritionInfo;
          servings: number;
          prep_time_minutes: number;
          cook_time_minutes: number;
          category: string;
          tags: string[];
          image_url: string | null;
          is_favorite: boolean;
          source: 'ai_generated' | 'manual' | 'imported';
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['recipes']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['recipes']['Insert']>;
      };
      meal_plans: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          start_date: string;
          end_date: string;
          days: MealPlanDay[];
          goals: DietaryGoals | null;
          family_member_ids: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['meal_plans']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['meal_plans']['Insert']>;
      };
      shopping_lists: {
        Row: {
          id: string;
          user_id: string;
          meal_plan_id: string | null;
          name: string;
          items: ShoppingItem[];
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['shopping_lists']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['shopping_lists']['Insert']>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}

// Supporting types
interface DietaryGoals {
  daily_calories?: number;
  protein_grams?: number;
  carbs_grams?: number;
  fat_grams?: number;
  fiber_grams?: number;
}

interface UserPreferences {
  language: 'en' | 'ru';
  cuisines?: string[];
  avoid_ingredients?: string[];
}

interface MemberPreferences {
  portion_size?: 'small' | 'regular' | 'large';
  allergies?: string[];
}

interface Ingredient {
  name: string;
  amount: number;
  unit: string;
  notes?: string;
}

interface NutritionInfo {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  sugar?: number;
  sodium?: number;
}

interface MealPlanDay {
  date: string;
  meals: {
    type: 'breakfast' | 'lunch' | 'dinner' | 'snack';
    recipe_id?: string;
    recipe_title?: string;
    notes?: string;
  }[];
}

interface ShoppingItem {
  id: string;
  name: string;
  amount: number;
  unit: string;
  category: string;
  checked: boolean;
  recipe_ids?: string[];
}
